### PR TITLE
Hack around cliargs to provide "help" flag

### LINKED ISSUE #697: Output --help to STDOUT
Currently the output of `--help` is directed to STDERR which is wrong per GNU guidelines and quite annoying when trying to look for something. One has to redirect `2>&1` before greping or paging the output.

### PR DESCRIPTION
**Pull request by TheMagician23**
Fixes #697

This change adds a check on the error returned from the `cliargs` library, and provides a "help" argument to the consumer code in `busted/runner.lua`.
It is based on the workaround used with the same library here: https://github.com/sile-typesetter/sile/pull/1737/files
except that the code in `busted/runner.lua` probably won't need to change if `cliargs` ever supports adding a `--help` flag in the "correct" way.

### CODE REVIEW

**Comment by alerque** [comment]
The upstream for cli_args has (since this PR was started) migrated the project to this org. I proposed this a long time ago but this PR made me ping the author again and this time it happened. Now that we *can fix upstream* I think we *should* fix this issue at the source and then just *use* it correctly in this project.

**Comment by TheMagician23** [comment]
Hi Caleb.

This is fantastic news! I saw that lua_cliargs badly needed to be migrated to lunarmodules when I did my intial research, I'm glad you managed to make it happen.
I'll write a fix for the issue upstream soon; once it's done I'll comment on the issue in the busted repo with a link to the upstream fix.
Once it's in, you can throw away my original PR. Let me know if you want me to write a proper usage patch for busted after that fix goes in.

- The Magician

**Comment by TheMagician23** [comment]
Okay, I've written a PR to improve the help system in lua_cliargs: https://github.com/lunarmodules/lua_cliargs/pull/78

**Review by alerque — APPROVED** [review]

File: busted/runner.lua [hunk 1]
```diff
@@ -41,6 +41,11 @@ return function(options)
     exit(1, forceExit)
   end
 
+  if cliArgs.help then
+    io.stdout:write(cliArgs.helpText)
```
Comment (Tieske) [inline busted/runner.lua:45]: just checking: does the help text include a trailing newline? `io.stdout:write()` will not automatically append one like `print()` does.

Comment (alerque) [reply busted/runner.lua:45]: Good catch, it does *not* include a trailing newline and is used elsewhere inline so it doesn't make sense to add it to the content. I just addressed this by explicitly concating a newline to it as we write it out, and also normalized away the one use of `print()` instead of `io.<streat>:write()` like we are using everywhere else in this module.

**Review by Tieske — APPROVED** [review]
